<%
	if ((session.getAttribute("user") == null)) {
%>
You are not logged in<br/>
<a href="triplelogin.jsp">Please Login</a>
<%} else {
%>
Welcome Admin <%=session.getAttribute("user")%> 
<a href='logout.jsp'>Log out</a>

<!-- Add Customer Form -->
<form action="adminAddCustomer.jsp" method="post">
    Customer ID: <input type="text" name="acc_id" /><br/>
    Username: <input type="text" name="username" /><br/>
    Password: <input type="password" name="password" /><br/>
    <input type="submit" value="Add Customer" />
</form>
<form action="adminDeleteCustomer.jsp" method="post">
    Delete Customer (input acc_id): <input type="text" name="acc_id" /><br/>
    <input type="submit" value="Delete Customer" />
</form>
<form action="adminAddCustomerRep.jsp" method="post">
    Rep ID: <input type="text" name="acc_id" /><br/>
    Username: <input type="text" name="username" /><br/>
    Password: <input type="password" name="password" /><br/>
    <input type="submit" value="Add Customer Rep" />
</form>
<form action="adminDeleteCustomerRep.jsp" method="post">
    Delete Customer Rep (input acc_id): <input type="text" name="acc_id" /><br/>
    <input type="submit" value="Delete Customer Rep" />
</form>
<form action="adminEditCustomer.jsp" method="post">
    Customer Account ID: <input type="text" name="acc_id" /><br/>
    New Username: <input type="text" name="new_username" /><br/>
    New Password: <input type="text" name="new_password" /><br/>
    <input type="submit" value="Edit Customer" />
</form>
<form action="adminEditCustomerRep.jsp" method="post">
    Customer Rep Account ID: <input type="text" name="acc_id" /><br/>
    New Username: <input type="text" name="new_username" /><br/>
    New Password: <input type="text" name="new_password" /><br/>
    <input type="submit" value="Edit Customer Rep" />
</form>
<form action="adminSalesReport.jsp" method="post">
    Sales Report Month (input integer representing month): <input type="text" name="month" /><br/>
    Sales Report Year: <input type="text" name="year" /><br/>
    <input type="submit" value="did u make money or not" />
</form>

<form action="adminReservationsListFlightNum2.jsp" method="post">
    <input type="submit" value="Reservations by flight number!" />
</form>

<form action="adminReservationsListCustomerName2.jsp" method="post">
    <input type="submit" value="Reservations by customer name!" />
</form>
<form action="adminRevenueFlight.jsp" method="post">
    Summary listing of revenue generated by a particular flight (input flight number): <input type="text" name="flight_num" /><br/>
    <input type="submit" value="Go!" />
</form>
<form action="adminRevenueAirline.jsp" method="post">
    Summary listing of revenue generated by a particular airline (input two letter id): <input type="text" name="two_letter_id" /><br/>
    <input type="submit" value="Go!" />
</form>
<form action="adminRevenueCustomer.jsp" method="post">
    Summary listing of revenue generated by a particular customer (input acc_id): <input type="text" name="acc_id" /><br/>
    <input type="submit" value="Go!" />
</form>
<form action="adminCustomerMostRevenue.jsp" method="post">
    Which customer made the most revenue?: 
    <input type="submit" value="Let's find out!" />
</form>
<form action="adminMostActiveFlights.jsp" method="post">
    Which flights are most active?: 
    <input type="submit" value="Let's find out!" />
</form>
<%
	}
%>

